name: HLSL Test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      OffloadTest-branch:
        description: 'Test Suite Branch'
        required: false
        default: 'main'
        type: string
      LLVM-branch:
        description: 'LLVM Branch'
        required: false
        default: 'main'
        type: string
      LLVM-fork:
        description: 'LLVM fork'
        required: false
        default: 'llvm'
        type: string
      DXC-branch:
        description: 'DXC Branch'
        required: false
        default: 'main'
        type: string
      BuildType:
        description: 'Build Type'
        required: false
        default: 'RelWithDebInfo'
        type: choice
        options:
        - Release
        - RelWithDebInfo
        - Debug
      TestTarget:
        required: false
        default: 'check-hlsl'
        type: string
      OS:
        required: true
        type: choice
        options:
        - macOS
        - windows
      SKU:
        required: true
        type: choice
        options:
        - macos
        - windows-amd
        - windows-intel
        - windows-nvidia
      LLVM-ExtraCMakeArgs:
        description: 'Extra CMake Args for LLVM'
        required: false
        default: ''
        type: string
  workflow_call:
    inputs:
      OffloadTest-branch:
        description: 'Test Suite Branch'
        required: false
        default: 'main'
        type: string
      LLVM-branch:
        description: 'LLVM Branch'
        required: false
        default: 'main'
        type: string
      LLVM-fork:
        description: 'LLVM For'
        required: false
        default: 'llvm'
        type: string
      DXC-branch:
        description: 'DXC Branch'
        required: false
        default: 'main'
        type: string
      OS:
        required: true
        type: string
      SKU:
        required: true
        type: string
      BuildType:
        description: 'Build Config'
        required: false
        default: 'RelWithDebInfo'
        type: string
      TestTarget:
        required: false
        default: 'check-hlsl'
        type: string
      LLVM-ExtraCMakeArgs:
        description: 'Extra CMake Args for LLVM'
        required: false
        default: ''
        type: string

jobs:
  build:
    permissions:
      checks: write
    runs-on: [self-hosted, "hlsl-${{ inputs.SKU }}"]
    steps:
      - name: Checkout DXC
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: Microsoft/DirectXShaderCompiler
          ref: ${{ inputs.DXC-branch }}
          path: DXC
          fetch-depth: 1
          submodules: true
      - name: Checkout LLVM
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: ${{ inputs.LLVM-fork }}/llvm-project
          ref: ${{ inputs.LLVM-branch }}
          path: llvm-project
          fetch-depth: 1
      - name: Checkout OffloadTest
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: llvm/offload-test-suite
          ref: ${{ inputs.OffloadTest-branch }}
          path: OffloadTest
          fetch-depth: 1
      - name: Checkout Golden Images
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: llvm/offload-golden-images
          ref: main
          path: golden-images
          fetch-depth: 1
      - name: Setup Windows x64
        if: inputs.OS == 'windows' && runner.arch != 'ARM64'
        uses: llvm/actions/setup-windows@89a8cf80982d830faab019237860b344a6390c30 # main
        with:
          arch: amd64
      - name: Setup Windows
        if: inputs.OS == 'windows' && runner.arch == 'ARM64'
        uses: llvm/actions/setup-windows@89a8cf80982d830faab019237860b344a6390c30 # main
        with:
          arch: arm64
      - name: Detect Clang
        id: Test-Clang
        shell: bash
        if: contains(inputs.TestTarget, 'clang')
        run: echo TEST_CLANG=On >> $GITHUB_OUTPUT
      - name: Build DXC
        run: |
            cd DXC
            mkdir build
            cd build
            cmake -G Ninja -DCMAKE_BUILD_TYPE=${{ inputs.BuildType }} -DLLVM_ENABLE_ASSERTIONS=On -C ${{ github.workspace }}/DXC/cmake/caches/PredefinedParams.cmake -C ${{ github.workspace }}/OffloadTest/cmake/caches/sccache.cmake -DHLSL_DISABLE_SOURCE_GENERATION=On ${{ github.workspace }}/DXC/
            ninja
      - name: Build LLVM
        run: |
            cd llvm-project
            mkdir build
            cd build
            cmake -G Ninja ${{ inputs.LLVM-ExtraCMakeArgs }} -DCMAKE_BUILD_TYPE=${{ inputs.BuildType }} -DLLVM_ENABLE_ASSERTIONS=On -C ${{ github.workspace }}/llvm-project/clang/cmake/caches/HLSL.cmake -C ${{ github.workspace }}/OffloadTest/cmake/caches/sccache.cmake -DDXC_DIR=${{ github.workspace }}/DXC/build/bin -DLLVM_EXTERNAL_OFFLOADTEST_SOURCE_DIR=${{ github.workspace }}/OffloadTest -DLLVM_EXTERNAL_PROJECTS="OffloadTest" -DLLVM_LIT_ARGS="--xunit-xml-output=testresults.xunit.xml -v" -DOFFLOADTEST_TEST_CLANG=${{steps.Test-Clang.outputs.TEST_CLANG || 'Off' }} -DGOLDENIMAGE_DIR=${{ github.workspace }}/golden-images ${{ github.workspace }}/llvm-project/llvm/
            ninja hlsl-test-depends
      - name: Dump GPU Info
        run: |
            cd llvm-project
            cd build
            ./bin/api-query
      - name: Run HLSL Tests
        run: |
            cd llvm-project
            cd build
            ninja check-hlsl-unit
            ninja ${{ inputs.TestTarget }}
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/macos@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2.21.0
        if: always() && inputs.OS == 'macOS'
        with:
          comment_mode: off
          files: llvm-project/build/**/testresults.xunit.xml
      #- name: Publish Test Results
      #  uses: EnricoMi/publish-unit-test-result-action/windows@34d7c956a59aed1bfebf31df77b8de55db9bbaaf # v2.21.0
      #  if: always() && inputs.OS == 'windows'
      #  with:
      #    comment_mode: off
      #    files: llvm-project/build/**/testresults.xunit.xml
