name: Execution Testing

permissions:
  contents: read

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  Exec-Tests-Windows:
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        SKU: [windows-intel]
        TestTarget: [check-hlsl-d3d12, check-hlsl-vk, check-hlsl-clang-d3d12, check-hlsl-clang-vk]

    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: ${{ matrix.SKU }}
      TestTarget: ${{ matrix.TestTarget }}
      OffloadTest-branch: ${{ github.event.pull_request.head.sha }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On

  Exec-Tests-Windows-Warp:
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        SKU: [windows-intel, windows-qc]
        TestTarget: [check-hlsl-warp-d3d12, check-hlsl-clang-warp-d3d12]

    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: ${{ matrix.SKU }}
      TestTarget: ${{ matrix.TestTarget }}
      OffloadTest-branch: ${{ github.event.pull_request.head.sha }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On

  Exec-Tests-Extra:
    permissions:
      contents: read
      checks: write
    if: contains( github.event.pull_request.labels.*.name, 'test-all')
    strategy:
      fail-fast: false
      matrix:
        SKU: [windows-nvidia, windows-amd, windows-qc]
        TestTarget: [check-hlsl-d3d12, check-hlsl-vk, check-hlsl-clang-d3d12, check-hlsl-clang-vk]

    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: ${{ matrix.SKU }}
      TestTarget: ${{ matrix.TestTarget }}
      OffloadTest-branch: ${{ github.event.pull_request.head.sha }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On

  Exec-Tests-MacOS:
    permissions:
      contents: read
      checks: write
    strategy:
      fail-fast: false
      matrix:
        SKU: [macos]
        TestTarget: [check-hlsl-mtl, check-hlsl-clang-mtl]

    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: macOS
      SKU: ${{ matrix.SKU }}
      TestTarget: ${{ matrix.TestTarget }}
      OffloadTest-branch: ${{ github.event.pull_request.head.sha }}
