name: Windows ARM64 D3D12 Warp DXC

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # run every 6 hours
  pull_request:
    paths:
     - .github/workflows/windows-qc-dxc-warp-d3d12.yaml

jobs:
  Windows-ARM64-D3D12-Warp-DXC:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-qc
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
