name: Windows Vulkan NVIDIA DXC

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *' # run every 2 hours
  pull_request:
    paths:
     - .github/workflows/window-nvidia-dxc-vk.yaml

jobs:
  Windows-VK-NVIDIA-DXC:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-nvidia
      BuildType: Debug
      TestTarget: check-hlsl-vk
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
