name: Windows D3D12 Warp Preview DXC

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
     - .github/workflows/windows-amd-dxc-warp-preview-d3d12.yaml

jobs:
  Windows-D3D12-Warp-DXC:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-amd
      BuildType: Debug
      TestTarget: check-hlsl-warp-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DWARP_VERSION=1.0.15-preview
