name: Windows ARM64 D3D12 Warp Clang

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # run every 6 hours
  pull_request:
    paths:
     - .github/workflows/windows-qc-clang-warp-d3d12.yaml

jobs:
  Windows-ARM64-D3D12-Warp-Clang:
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-qc
      TestTarget: check-hlsl-clang-warp-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl -DOFFLOADTEST_USE_CLANG_TIDY=On
