name: Windows D3D12 QC DXC

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # run every 6 hours
  pull_request:
    paths:
     - .github/workflows/windows-qc-dxc-d3d12.yaml

jobs:
  Windows-D3D12-QC-DXC:
    uses: ./.github/workflows/build-and-test-callable.yaml
    with:
      OS: windows
      SKU: windows-qc
      BuildType: Debug
      TestTarget: check-hlsl-d3d12
      OffloadTest-branch: ${{ github.ref }}
      LLVM-ExtraCMakeArgs: -DCMAKE_C_COMPILER=clang-cl -DCMAKE_CXX_COMPILER=clang-cl
